"""AST → Python module string. Top-level dispatcher.

v0.6 骨架: emit a runnable Python module with:
  - one Python function per ``code`` node (body verbatim from BlockScalar)
  - one stub function per ``agent`` node (calls into runtime.agent_bridge)
  - one ``SetDefinition`` literal per ``set`` node
  - one orchestrator entry function per ``flow`` node

The runtime helpers are imported from ``al.runtime`` (currently
mostly [TODO] stubs — see docs/PROJECT_PLAN.md 阶段 ②).
"""

from __future__ import annotations

from io import StringIO

from al.parser.ast_nodes import Program, Definition
from al.codegen.emit_code import emit_code_node
from al.codegen.emit_agent import emit_agent_node
from al.codegen.emit_set import emit_set_node
from al.codegen.emit_flow import emit_flow_node


PREAMBLE = '''"""Generated by al.codegen — do not edit by hand.

Source: {source_name}
"""

from al.runtime import (
    agent_call,           # [TODO] arrives in 阶段 ②
    flow_call,            # [TODO] arrives in 阶段 ②
    SetDefinition,        # [TODO] arrives in 阶段 ②
)
'''


def emit_python(program: Program, source_name: str = "<unknown>") -> str:
    """Emit a complete Python module from a parsed AST.

    Output is intended to be importable, but most runtime hooks are stubs
    until 阶段 ②. Use this in 阶段 ③ to feed Commit0 pytest harness.
    """
    out = StringIO()
    out.write(PREAMBLE.format(source_name=source_name))
    out.write("\n\n")

    # Emit in dependency-friendly order: set → code → agent → flow
    # (sets first so agents can reference them; flows last because they
    # call everything else.)
    by_kind: dict[str, list[Definition]] = {"set": [], "code": [], "agent": [], "flow": []}
    for d in program.defs:
        by_kind[d.kind].append(d)

    for d in by_kind["set"]:
        out.write(emit_set_node(d))
        out.write("\n\n")
    for d in by_kind["code"]:
        out.write(emit_code_node(d))
        out.write("\n\n")
    for d in by_kind["agent"]:
        out.write(emit_agent_node(d))
        out.write("\n\n")
    for d in by_kind["flow"]:
        out.write(emit_flow_node(d))
        out.write("\n\n")

    return out.getvalue()
